### ISSUE TITLE
Error with compose

### ISSUE THREAD

**Issue by lemito** [mikhail-karpov/blogging-network#18]
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by mikhail-karpov** [comment]
As far as I can see from the link you've provided, Docker version 3.8 is supported. My Docker Engine version is 20.10.12 and I got no errors. I also tried version 3.3 and got no errors, neither during build stage nor during running.

My journey is Docker started recently, and I'm not an expert int it. Do you still recommend to swith to version 3.3?
