### ISSUE TITLE
user-feed-service 

### ISSUE THREAD

**Issue by ertmnv** [mikhail-karpov/blogging-network#20]
Hello, Mikhail!
Could you please explain when userFeedService.generateUserFeed and userFeedService.getUserFeed will be called?

**Comment by mikhail-karpov** [comment]
Hello!
They are called in controller
https://github.com/mikhail-karpov/blogging-network/blob/master/user-feed-service/src/main/java/com/mikhailkarpov/bloggingnetwork/feed/api/UserFeedController.java
